language: node_js
node_js:
  - "node"
script:
  - echo "Entering /backend/..."
  - cd backend
  - echo "Deploying..."
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $SECRET_FIREBASE_TOKEN